config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotes#index"
  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path, notice: "Quote was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy
    
    respond_to do |format|
      format.html {  redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "space-y-5" } do |f| %>
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "bg-orange-600 text-white px-5 py-2 text-xl inline-block" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="flex justify-between my-5">
    <%= link_to quote.name, quote_path(quote), data: { turbo_frame: "_top"} %>
    <div class="flex gap-5">
      <%= button_to "Delete", quote_path(quote), method: :delete, class: "" %>
      <%= link_to "Edit", edit_quote_path(quote), class: "" %>
    </div>
  </div>
<% end %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.erb
<main class="container mx-auto">
  <%= link_to sanitize("&larr; Back to quotes"), quote_path(@quote) %>

  <header class="">
    <h1>Edit quote</h1>
  </header>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<main class="container mx-auto mt-20">
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <header class="flex justify-between">
      <h1 class="text-3xl">Quotes</h1>
      <%= link_to "New quote", new_quote_path, class: 'text-orange-500' %>
    </header>
  <% end %>

  <%= render @quotes %>
</main>

app/views/quotes/new.html.erb
<main class="container mx-auto mt-20">


  <header class="flex gap-5 items-center my-10">
    <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
    <h1 class="text-3xl">New quote</h1>
  </header>

  <%= render "form", quote: @quote %>
</main>

app/views/quotes/show.html.erb
<main class="container mx-auto mt-20">
  <header class="flex gap-5 items-center">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
    <h1 class="text-3xl"><%= @quote.name %></h1>
  </header>
</main>